[package]
name = "prj-choco"
version = "0.1.0"
edition = "2021"

# このプロジェクトで使用するRustエディション。"2015"、"2018"、または"2021"があります。
# エディションについての詳細は、Rustのドキュメントを参照してください。

# 以下は依存関係のセクションです。プロジェクトで外部のクレートを使用する場合、ここに追加します。
[dependencies]
