version: '3.7'
services:
  rust-web-app:
    container_name: rust-web-app
    build:
      context: ./Dockerfiles
      dockerfile: Dockerfile.rust
    ports:
      - 8080:8080
    volumes:
      - ./app:/app
